"""auto-vote

Revision ID: ab54b090c8f3
Revises: 457b9cb6d099
Create Date: 2022-08-30 19:45:48.923024

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ab54b090c8f3'
down_revision = '457b9cb6d099'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
